version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud:26.0.0
    container_name: nextcloud
    ports:
      - "8080:80"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    depends_on:
      - db
    volumes:
      - nextcloud_data:/var/www/html

volumes:
  db_data: {}
  nextcloud_data: {}
